/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** One record-type count from [`JsDecodeStats`]. */
export interface JsRecordTypeCount {
  /** DBN record type name. */
  recordType: string
  /** Records of this type. */
  count: bigint
}
/** One bounded sequence-discontinuity sample. */
export interface JsSequenceDiscontinuity {
  /** Databento publisher identifier. */
  publisherId: number
  /** MBO channel identifier when present. */
  channelId?: number
  /** Previous venue sequence number. */
  previous: number
  /** Current venue sequence number. */
  current: number
  /** Current record timestamp in Unix nanoseconds. */
  timestampNs: bigint
  /** `forward_gap`, `duplicate`, or `regression`. */
  kind: string
  /** Missing venue sequence values for a forward gap. */
  missing: bigint
}
/** Sequence diagnostics returned to JavaScript. */
export interface JsSequenceStats {
  /** Records that carried sequence numbers. */
  recordsObserved: bigint
  /** Forward sequence discontinuities. */
  forwardGapCount: bigint
  /** Total missing sequence values. */
  missingSequenceCount: bigint
  /** Repeated sequence values. */
  duplicateCount: bigint
  /** Backward sequence movements. */
  regressionCount: bigint
  /** First one hundred sampled discontinuities. */
  samples: Array<JsSequenceDiscontinuity>
  /** Whether more samples were omitted. */
  samplesTruncated: boolean
  /** Interpretation warning for filtered symbol streams. */
  interpretation: string
}
/** Streaming decode diagnostics returned to JavaScript. */
export interface JsDecodeStats {
  /** Input path. */
  path: string
  /** DBN metadata schema. */
  schema?: string
  /** Total decoded records. */
  recordCount: bigint
  /** Counts by DBN record type. */
  recordCountsByType: Array<JsRecordTypeCount>
  /** First stream timestamp in Unix nanoseconds. */
  firstTimestampNs?: bigint
  /** Last stream timestamp in Unix nanoseconds. */
  lastTimestampNs?: bigint
  /** Minimum timestamp in Unix nanoseconds. */
  minTimestampNs?: bigint
  /** Maximum timestamp in Unix nanoseconds. */
  maxTimestampNs?: bigint
  /** Records whose timestamp regressed. */
  timestampRegressionCount: bigint
  /** Sequence diagnostics when the schema carries venue sequence numbers. */
  sequence?: JsSequenceStats
}
/** One owned MBO record yielded across the N-API boundary. */
export interface JsMboRecord {
  /** Exchange event timestamp in Unix nanoseconds. */
  timestampEventNs: bigint
  /** Capture-server receive timestamp in Unix nanoseconds. */
  timestampReceiveNs: bigint
  /** Databento publisher identifier. */
  publisherId: number
  /** Numeric instrument identifier. */
  instrumentId: number
  /** Venue order identifier. */
  orderId: bigint
  /** Fixed-point price in units of 1e-9. */
  price: bigint
  /** Order quantity. */
  size: number
  /** Raw DBN flag bitset. */
  flags: number
  /** Channel identifier. */
  channelId: number
  /** Canonical DBN action character. */
  action: string
  /** Canonical DBN side character. */
  side: string
  /** Receive-to-send delta. */
  timestampInDelta: number
  /** Venue message sequence. */
  sequence: number
}
/** Four-parameter sweep configuration accepted from JavaScript. */
export interface JsSweepConfig {
  /** Number of earlier trades in the rolling extreme. */
  lookbackTrades: number
  /** Minimum extreme penetration in ticks. */
  thresholdTicks: number
  /** Maximum reversion window in milliseconds. */
  reversionWindowMs: number
  /** Instrument tick size in DBN fixed-price units. */
  tickSize: number
}
/** One liquidity sweep returned to JavaScript. */
export interface JsSweepEvent {
  /** Databento publisher identifier. */
  publisherId: number
  /** Numeric instrument identifier. */
  instrumentId: number
  /** Emission timestamp in Unix nanoseconds. */
  timestampNs: bigint
  /** Threshold-crossing timestamp in Unix nanoseconds. */
  sweepTimestampNs: bigint
  /** Reversion timestamp in Unix nanoseconds. */
  reversionTimestampNs: bigint
  /** `above_high` or `below_low`. */
  direction: string
  /** Swept fixed-point price level. */
  sweptLevel: bigint
  /** Maximum displacement beyond the level. */
  displacementTicks: bigint
  /** Elapsed sweep duration in nanoseconds. */
  durationNs: bigint
  /** Visible size consumed at the swept level. */
  restingSizeConsumed: bigint
}
/**
 * Decodes one DBN file and returns the same core statistics used by the Rust CLI.
 *
 * # Errors
 * Throws a JavaScript error when the DBN decoder rejects the file.
 */
export declare function decodeStats(path: string): JsDecodeStats
/**
 * File-backed MBO decoder. Each call owns only the returned record; the remaining
 * input stays in the Rust decoder and is never loaded into a JavaScript array.
 */
export declare class MboDecoder {
  /**
   * Opens an MBO DBN or DBN.ZST file.
   *
   * # Errors
   * Throws when the file is malformed or declares another schema.
   */
  constructor(path: string)
  /**
   * Returns the next owned record or `null` at end of stream.
   *
   * # Errors
   * Throws when decoding the next record fails.
   */
  nextRecord(): JsMboRecord | null
  /** Number of records yielded so far. */
  get recordsRead(): bigint
}
/**
 * Stateful sweep scanner over a file-backed MBO stream and reconstructed book.
 * Each call scans until one event is available or the input ends.
 */
export declare class MboSweepDetector {
  /**
   * Opens an MBO stream and validates the four detector parameters.
   *
   * # Errors
   * Throws for invalid parameters, malformed input, or a non-MBO schema.
   */
  constructor(path: string, config: JsSweepConfig)
  /**
   * Returns the next completed sweep or `null` at end of stream.
   *
   * # Errors
   * Throws on malformed DBN, invalid action bytes, timestamp regression, or an
   * inconsistent order-book transition.
   */
  nextSweep(): JsSweepEvent | null
  /** Number of MBO records scanned so far. */
  get recordsScanned(): bigint
}
